name: Build on CentOS7 (split jobs)

on:
  push:
    branches: [ main, v3.2 ]
  pull_request:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      src-path: ${{ github.workspace }}
    steps:
      - name: Checkout 源码
        uses: actions/checkout@v3

      - name: 打包源码 Artifact
        uses: actions/upload-artifact@v3
        with:
          name: source
          path: .

  build:
    needs: checkout
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
      - name: 下载源码 Artifact
        uses: actions/download-artifact@v3
        with:
          name: source
          path: .

      - name: 安装依赖并编译
        run: |
          yum -y update
          yum -y groupinstall "Development Tools"
          yum -y install openssl-devel libstdc++-devel python2 centos-release-scl devtoolset-8
          source /opt/rh/devtoolset-8/enable
          python2 buildscripts/scons.py --ssl --dbg --clean mongod
          python2 buildscripts/scons.py --ssl --dbg mongod
