name: Build on CentOS 7 via Docker (OpenSSL 静态链接)

on:
  push:
    branches: [ main, v3.2 ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 源码
        uses: actions/checkout@v3

      - name: 在 CentOS 7 容器里并行静态编译 MongoDB（OpenSSL 静态）
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/workspace \
            -w /workspace \
            centos:7 \
            bash -lc "\
              # 修复老旧镜像仓库到 vault.centos.org
              sed -i \
                -e 's|^mirrorlist=|#mirrorlist=|g' \
                -e 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' \
                /etc/yum.repos.d/CentOS-*.repo && \
              # 安装工具链及 OpenSSL 静态库
              yum -y update && \
              yum -y groupinstall 'Development Tools' && \
              yum -y install openssl-devel openssl-static libstdc++-devel python2 git && \
              # 并行任务数
              JOBS=$(nproc) && echo \"Using $JOBS jobs for scons\" && \
              # 编译：--link-model=static 静态链接 C++ 库，LINKFLAGS 强制静态链接 libssl/libcrypto
              python2 buildscripts/scons.py \
                --ssl \
                --link-model=static \
                --dbg \
                mongod \
                MONGO_VERSION=3.2.22 \
                LINKFLAGS=\"-Wl,-Bstatic -lssl -lcrypto -Wl,-Bdynamic\" \
                -j 8\
            "

      - name: 上传静态编译产物
        uses: actions/upload-artifact@v4
        with:
          name: mongod-static
          path: |
            **/mongod
            mongod
