# .github/workflows/centos7-build.yml
name: Build on CentOS 7 via Docker

on:
  push:
    branches: [ main, v3.2 ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 源码（含完整 Git 历史 & tags）
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 在 CentOS 7 容器里编译 MongoDB
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/workspace \
            -w /workspace \
            centos:7 \
            bash -lc "\
              # 修复 yum 仓库到 vault.centos.org
              sed -i \
                -e 's|^mirrorlist=|#mirrorlist=|g' \
                -e 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' \
                /etc/yum.repos.d/CentOS-*.repo && \
              # 安装工具链
              yum -y update && \
              yum -y groupinstall 'Development Tools' && \
              yum -y install openssl-devel libstdc++-devel python2 git && \
              # 推断版本号
              VER=$(git describe --tags --abbrev=0 | sed 's/^r//') && \
              echo \"Building MongoDB version $VER\" && \
              # 清理并编译
              python2 buildscripts/scons.py --ssl --dbg --clean mongod MONGO_VERSION=$VER && \
              python2 buildscripts/scons.py --ssl --dbg mongod MONGO_VERSION=$VER\
            "

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: mongod-debug
          path: |
            **/mongod       # 任意目录下的 mongod 二进制
            mongod          # 也可匹配到根目录下的 mongod

