# .github/workflows/centos7-build.yml
name: Build on CentOS 7 via Docker

on:
  push:
    branches: [ main, v3.2 ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 源码
        uses: actions/checkout@v3

      - name: 下载源码 Artifact
        uses: actions/download-artifact@v4
        # with:
        #   name: source
        #   path: .

      # 如果你不需要 upload/download-artifact，直接删掉上面这块，
      # checkout 完了以后源码就已经在 $GITHUB_WORKSPACE 里了。

      - name: 在 CentOS 7 容器里编译 MongoDB
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/workspace \
            -w /workspace \
            centos:7 \
            bash -lc "\
              yum -y update && \
              yum -y groupinstall 'Development Tools' && \
              yum -y install openssl-devel libstdc++-devel python2 centos-release-scl devtoolset-8 && \
              source /opt/rh/devtoolset-8/enable && \
              python2 buildscripts/scons.py --ssl --dbg --clean mongod && \
              python2 buildscripts/scons.py --ssl --dbg mongod\
            "
