name: Build on CentOS 7 via Docker

on:
  push:
    branches: [ main, v3.2 ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 源码
        uses: actions/checkout@v3

      - name: 在 CentOS 7 容器里编译 MongoDB
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/workspace \
            -w /workspace \
            centos:7 \
            bash -lc "\
              # 1) 修复老旧镜像仓库指向 vault.centos.org
              sed -i \
                -e 's|^mirrorlist=|#mirrorlist=|g' \
                -e 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' \
                /etc/yum.repos.d/CentOS-*.repo && \
              # 2) 安装开发工具链（默认 GCC 4.8.5 足以通过 ≥4.8.2 检测）
              yum -y update && \
              yum -y groupinstall 'Development Tools' && \
              yum -y install openssl-devel libstdc++-devel python2 && \
              # 3) 清理旧构建并编译
              python2 buildscripts/scons.py --ssl --dbg --clean mongod MONGO_VERSION=3.2.22 && \
              python2 buildscripts/scons.py --ssl --dbg mongod MONGO_VERSION=3.2.22 \
            "
