name: Build on CentOS 7 via Docker

on:
  push:
    branches: [ main, v3.2 ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 源码
        uses: actions/checkout@v3

      - name: 在 CentOS 7 容器里并行编译 MongoDB
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/workspace \
            -w /workspace \
            centos:7 \
            bash -lc "\
              # 修复老旧镜像仓库到 vault.centos.org
              sed -i \
                -e 's|^mirrorlist=|#mirrorlist=|g' \
                -e 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' \
                /etc/yum.repos.d/CentOS-*.repo && \
              # 安装开发工具链
              yum -y update && \
              yum -y groupinstall 'Development Tools' && \
              yum -y install openssl-devel libstdc++-devel python2 && \
              # 取出并行线程数
              JOBS=$(nproc) && \
              echo \"Using $JOBS parallel jobs for scons\" && \
              # 清理并使用 -j 参数并行编译
              python2 buildscripts/scons.py --ssl --dbg --clean mongod MONGO_VERSION=3.2.22 -j $JOBS && \
              python2 buildscripts/scons.py --ssl --dbg mongod MONGO_VERSION=3.2.22 -j $JOBS\
            "

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: mongod-debug
          path: |
            **/mongod
            mongod
