name: Build on CentOS 7 via Docker

on:
  push:
    branches: [ main, v3.2 ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 源码
        uses: actions/checkout@v3

      - name: 在 CentOS 7 容器里编译 MongoDB
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/workspace \
            -w /workspace \
            centos:7 \
            bash -lc "\
              # 修复官方镜像已迁移到 vault.centos.org 的仓库 URL
              sed -i \
                -e 's|^mirrorlist=|#mirrorlist=|g' \
                -e 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' \
                /etc/yum.repos.d/CentOS-*.repo && \
              yum -y update && \
              yum -y groupinstall 'Development Tools' && \
              yum -y install openssl-devel libstdc++-devel python2 centos-release-scl devtoolset-8 && \
              # 启用新版 GCC
              source /opt/rh/devtoolset-8/enable && \
              # 清理并编译
              python2 buildscripts/scons.py --ssl --dbg --clean mongod && \
              python2 buildscripts/scons.py --ssl --dbg mongod\
            "
